Update ResolveSymbolLookup error message to be more helpful.
These are the errors that are returned when we unsuccessfully attempt
to mangle a function name to the full symbol. I find that in practice,
this usually fails due to not providing the correct arguments.

Old message:
Query: create function udf_count(bigint) returns int location '/test-warehouse/libudasample.so' symbol='CountUpdate'
ERROR: AnalysisException: Could not find symbol 'CountUpdate' in: /test-warehouse/libudasample.so
Could not find symbol.

New UDF message:
Query: create function udf_count(bigint) returns int location '/test-warehouse/libudasample.so' symbol='CountUpdate'
ERROR: AnalysisException: Could not find function CountUpdate(BIGINT) in: hdfs://localhost:20500/test-warehouse/libudasample.so
Check that symbol and argument types are correct.

New UDA message:
Query: create aggregate function udf_count(bigint) returns int location '/test-warehouse/libudasample.so' update_fn='CountUpdate'
ERROR: AnalysisException: Could not find function CountUpdate(BIGINT) returns INT in: hdfs://localhost:20500/test-warehouse/libudasample.so
Check that function name, arguments, and return type are correct.

New message with full symbol:
Query: create aggregate function udf_count(bigint) returns int location '/test-warehouse/libudasample.so' update_fn='_Zasdf'
ERROR: AnalysisException: Could not find symbol '_Zasdf' in: hdfs://localhost:20500/test-warehouse/libudasample.so

Change-Id: I602db6d3786f8351364ce8272b7dd930e04f5b51
Reviewed-on: http://gerrit.ent.cloudera.com:8080/1009
Reviewed-by: Skye Wanderman-Milne <skye@cloudera.com>
Tested-by: jenkins